# Generated by Django 4.2.13 on 2026-04-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalGSTR2BEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_matched', models.BooleanField(default=False)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('missing_in_books', 'Missing in Books'), ('missing_in_portal', 'Missing in Portal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_gstr2b_entries', to='core.company')),
            ],
            options={
                'verbose_name': 'Portal GSTR-2B Entry',
                'verbose_name_plural': 'Portal GSTR-2B Entries',
                'unique_together': {('company', 'gstin', 'invoice_number', 'invoice_date')},
            },
        ),
    ]
