# Generated by Codex on 2026-05-02

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def populate_updated_at(apps, schema_editor):
    PortalGSTR2BEntry = apps.get_model("gstr2b", "PortalGSTR2BEntry")
    PortalGSTR2BEntry.objects.filter(updated_at__isnull=True).update(updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("gstr2b", "0001_initial"),
        ("vouchers", "0025_voucher_number_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalgstr2bentry",
            name="action_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="portalgstr2bentry",
            name="action_status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("accepted", "Accepted"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="portalgstr2bentry",
            name="match_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portalgstr2bentry",
            name="matched_voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portal_gstr2b_matches",
                to="vouchers.voucher",
            ),
        ),
        migrations.AddField(
            model_name="portalgstr2bentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(populate_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="portalgstr2bentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
