# Generated by Django 4.2.13 on 2026-04-16 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0014_ledger_credit_days_ledger_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='ledger.ledger')),
            ],
        ),
    ]
