# Generated by Django 4.2.13 on 2026-04-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_ledger_credit_days_ledger_credit_limit'),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.ledger')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='portal.portaluser')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
