# Generated by Django 4.2.13 on 2026-05-02 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gstperiodreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0007_ocrsubmission_source'),
        ('portal', '0003_balanceconfirmation_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('document_type', models.CharField(choices=[('gst_invoice', 'GST Invoice / Bill'), ('gst_notice', 'GST Notice Evidence'), ('tds', 'TDS Document'), ('bank', 'Bank Statement'), ('ledger_confirmation', 'Ledger Confirmation'), ('other', 'Other Document')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('uploaded', 'Uploaded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('response_note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_document_requests', to='core.company')),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_requests', to='portal.portaluser')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_document_requests', to='core.practicetask')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_document_requests', to=settings.AUTH_USER_MODEL)),
                ('uploaded_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_document_requests', to='ocr.ocrsubmission')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'due_date'], name='portal_docreq_cmp_stat_idx'), models.Index(fields=['source_reference'], name='portal_docreq_source_idx')],
            },
        ),
    ]
