# Generated by Django 4.2.13 on 2026-03-27 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal_finance', '0002_personalbudget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalbudget',
            options={'ordering': ['category__name']},
        ),
        migrations.AlterModelOptions(
            name='personalcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Personal Categories'},
        ),
        migrations.AlterModelOptions(
            name='personalexpense',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='personalexpense',
            name='created_at',
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='item_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='personalexpense',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='PersonalFinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('billing_start_day', models.PositiveSmallIntegerField(default=1)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalExpenseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.CharField(default='Cash', max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_finance.personalcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
