# Generated by Django 4.2.13 on 2026-03-24 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(blank=True, help_text='15-character GST Identification Number (optional)', max_length=15, null=True, verbose_name='GSTIN')),
                ('address', models.TextField(blank=True, null=True)),
                ('short_code', models.CharField(blank=True, help_text='Used in voucher number prefix, e.g. ABC for ABC Corp', max_length=6)),
                ('financial_year_start', models.DateField(blank=True, help_text='e.g. 2024-04-01', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Accountant', 'Accountant'), ('Viewer', 'Viewer')], default='Accountant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Company Access',
                'verbose_name_plural': 'User Company Access',
                'ordering': ['company__name'],
                'unique_together': {('user', 'company')},
            },
        ),
    ]
