# Generated by Django 5.2.12 on 2026-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, help_text='e.g. State Bank of India', max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='11-character IFSC code, e.g. SBIN0001234', max_length=11, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AddField(
            model_name='company',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g. business@ybl — used to generate Pay-Now QR on Sales invoices', max_length=50, null=True, verbose_name='UPI ID'),
        ),
    ]
