# Generated by Django 5.2.12 on 2026-03-26 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_bank_upi_fields'),
        ('ledger', '0003_ledger_gstin'),
        ('vouchers', '0004_voucher_gst_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(help_text='Period covered — usually the last date of the statement.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('account_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='ledger.ledger', verbose_name='Bank Account Ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='core.company')),
            ],
            options={
                'verbose_name': 'Bank Statement',
                'verbose_name_plural': 'Bank Statements',
                'ordering': ['-statement_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, help_text='Amount withdrawn / paid out.', max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, help_text='Amount deposited / received.', max_digits=15)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Running balance from the bank statement.', max_digits=15, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('row_number', models.PositiveIntegerField(default=0, help_text='Row order in the CSV.')),
                ('matched_voucher', models.ForeignKey(blank=True, help_text='Voucher this row was matched / reconciled against.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_matches', to='vouchers.voucher')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.bankstatement')),
            ],
            options={
                'verbose_name': 'Bank Statement Row',
                'verbose_name_plural': 'Bank Statement Rows',
                'ordering': ['row_number'],
            },
        ),
    ]
