# Generated by Django 4.2.13 on 2026-03-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bank_reconciliation'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={('company', 'timestamp')},
        ),
    ]
