# Generated by Django 4.2.13 on 2026-04-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_index_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_company_def1b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_model_n_3fb686_idx',
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_id',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='auditlog',
            index_together={('model_name', 'record_id')},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
    ]
