# Generated by Django 4.2.13 on 2026-04-13 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_ledger_address'),
        ('core', '0006_remove_auditlog_core_auditl_company_def1b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementrow',
            name='suggested_ledger',
            field=models.ForeignKey(blank=True, help_text='Intelligently suggested ledger based on description matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_suggestions', to='ledger.ledger'),
        ),
        migrations.AddField(
            model_name='company',
            name='portal_token',
            field=models.CharField(blank=True, help_text='A secure token for the client upload portal.', max_length=64, null=True, unique=True),
        ),
    ]
