# Generated by Django 4.2.13 on 2026-04-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bankstatementrow_suggested_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_valuation_method', models.CharField(choices=[('WAC', 'Weighted Average Cost'), ('FIFO', 'First-In, First-Out')], default='WAC', max_length=10)),
                ('track_inventory_by_default', models.BooleanField(default=True)),
                ('auto_create_tax_lines', models.BooleanField(default=True, help_text='Automatically create GST lines based on StockItem tax rates.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.company')),
            ],
        ),
    ]
