# Generated by Django 4.2.13 on 2026-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='books_closed_until',
            field=models.DateField(blank=True, help_text='Period Locking: No vouchers can be created or edited on or before this date.', null=True),
        ),
    ]
