# Generated by Django 4.2.13 on 2026-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companysettings_books_closed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='bank_locked_until',
            field=models.DateField(blank=True, help_text='Bank Locking: No bank vouchers can be created or edited on or before this date.', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='inventory_locked_until',
            field=models.DateField(blank=True, help_text='Inventory Locking: No stock vouchers can be created or edited on or before this date.', null=True),
        ),
    ]
