# Generated by Django 4.2.13 on 2026-05-02 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_practicetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GSTR9', 'GSTR-9'), ('GSTR9C', 'GSTR-9C'), ('GST_IMS', 'GST IMS Review'), ('TDS_PAYMENT', 'TDS Payment'), ('TDS_24Q', 'TDS 24Q'), ('TDS_26Q', 'TDS 26Q'), ('FORM16', 'Form 16'), ('ITR', 'ITR'), ('MCA_AOC4', 'MCA AOC-4'), ('MCA_MGT7', 'MCA MGT-7'), ('TAX_AUDIT', 'Tax Audit'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('client_pending', 'Client Pending'), ('ready_for_review', 'Ready for Review'), ('blocked', 'Blocked'), ('filed', 'Filed'), ('cancelled', 'Cancelled')], default='not_started', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('calendar', 'Calendar Template'), ('portal', 'Portal'), ('import', 'Import')], default='manual', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=160)),
                ('arn_ack_number', models.CharField(blank=True, max_length=160, verbose_name='ARN / Ack Number')),
                ('portal_status', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_filings', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_filings', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_filings', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_compliance_filings', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_filings', to='core.practicetask')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_compliance_filings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', 'company__name', 'filing_type'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(choices=[('GST', 'GST'), ('TDS', 'TDS'), ('INCOME_TAX', 'Income Tax'), ('MCA', 'MCA'), ('AUDIT', 'Audit'), ('CLIENT', 'Client Query'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('reference_number', models.CharField(blank=True, max_length=160)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('response_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_review', 'In Review'), ('data_pending', 'Data Pending'), ('response_ready', 'Response Ready'), ('responded', 'Responded'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='received', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='high', max_length=20)),
                ('portal_status', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('response_summary', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_compliance_notices', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_compliance_notices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_notices', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compliance_notices', to=settings.AUTH_USER_MODEL)),
                ('related_filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.compliancefiling')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_notices', to='core.practicetask')),
            ],
            options={
                'ordering': ['status', 'response_due_date', '-priority', 'company__name'],
                'indexes': [models.Index(fields=['company', 'notice_type', 'response_due_date'], name='core_notice_cmp_type_due_idx'), models.Index(fields=['status', 'response_due_date'], name='core_notice_status_due_idx'), models.Index(fields=['assigned_to', 'status', 'response_due_date'], name='core_notice_owner_stat_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='compliancefiling',
            index=models.Index(fields=['company', 'filing_type', 'period_start'], name='core_fil_cmp_typ_per_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefiling',
            index=models.Index(fields=['status', 'due_date'], name='core_filing_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancefiling',
            index=models.Index(fields=['assigned_to', 'status', 'due_date'], name='core_filing_owner_stat_idx'),
        ),
    ]
