# Generated by Django 4.2.13 on 2026-05-02 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_compliancefiling_compliancenotice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTPeriodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('signed_off', 'Signed Off'), ('reopened', 'Reopened')], default='open', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_period_reviews', to='core.company')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_gst_period_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_gst_period_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'company__name'],
                'indexes': [models.Index(fields=['company', 'period_start'], name='core_gst_review_period_idx'), models.Index(fields=['status', 'period_start'], name='core_gst_review_status_idx')],
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
    ]
