# Generated by Django 4.2.13 on 2026-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_gstperiodreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementrow',
            name='duplicate_group_key',
            field=models.CharField(blank=True, db_index=True, help_text='Internal duplicate-detection grouping key.', max_length=160),
        ),
        migrations.AddField(
            model_name='bankstatementrow',
            name='match_confidence',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100 confidence score from bank reconciliation matching.'),
        ),
        migrations.AddField(
            model_name='bankstatementrow',
            name='match_reason',
            field=models.CharField(blank=True, help_text='Short explanation for the match or suggestion.', max_length=160),
        ),
        migrations.AddField(
            model_name='bankstatementrow',
            name='potential_duplicate',
            field=models.BooleanField(default=False, help_text='Flags rows that look duplicated across uploaded bank statements.'),
        ),
    ]
