# Generated by Django 4.2.13 on 2026-05-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0015_bankstatementrow_duplicate_group_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilingReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("GST_MONTHLY", "GST Monthly"),
                            ("TDS_QUARTERLY", "TDS Quarterly"),
                            ("ITR", "ITR"),
                            ("MCA", "MCA"),
                            ("TAX_AUDIT", "Tax Audit"),
                            ("OTHER", "Other"),
                        ],
                        default="GST_MONTHLY",
                        max_length=30,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("under_review", "Under Review"),
                            ("reviewed", "Reviewed"),
                            ("sent_back", "Sent Back"),
                            ("approved_for_filing", "Approved for Filing"),
                            ("reopened", "Reopened"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("readiness_score", models.PositiveSmallIntegerField(default=0)),
                ("risk_score", models.PositiveSmallIntegerField(default=0)),
                ("blocker_snapshot", models.JSONField(blank=True, default=dict)),
                ("waived_blockers", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("sent_back_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_filing_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_reviews",
                        to="core.company",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_filing_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_filing_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_back_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_back_filing_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-period_start", "company__name"],
                "indexes": [
                    models.Index(fields=["company", "review_type", "period_start"], name="core_frev_cmp_typ_per_idx"),
                    models.Index(fields=["status", "period_start"], name="core_frev_status_period_idx"),
                    models.Index(fields=["approved_by", "approved_at"], name="core_frev_approver_idx"),
                ],
                "unique_together": {("company", "review_type", "period_start", "period_end")},
            },
        ),
    ]
