# Generated by Django 4.2.13 on 2026-05-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0016_filingreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSTFilingPack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready"),
                            ("filed", "Filed"),
                            ("reopened", "Reopened"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                ("summary_snapshot", models.JSONField(blank=True, default=dict)),
                ("validation_snapshot", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("arn_ack_number", models.CharField(blank=True, max_length=160, verbose_name="ARN / Ack Number")),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_filing_packs",
                        to="core.company",
                    ),
                ),
                (
                    "filed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filed_gst_filing_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_gst_filing_packs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gst_filing_packs",
                        to="core.filingreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "company__name"],
                "indexes": [
                    models.Index(fields=["company", "period_start"], name="core_gst_pack_company_idx"),
                    models.Index(fields=["status", "period_start"], name="core_gst_pack_status_idx"),
                    models.Index(fields=["filed_by", "filed_at"], name="core_gst_pack_filed_idx"),
                ],
                "unique_together": {("company", "period_start", "period_end")},
            },
        ),
    ]
