# Generated by Django 4.2.13 on 2026-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_gstfilingpack'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tan',
            field=models.CharField(blank=True, help_text='10-character Tax Deduction and Collection Account Number (optional)', max_length=10, null=True, verbose_name='TAN'),
        ),
        migrations.AddField(
            model_name='company',
            name='tds_responsible_designation',
            field=models.CharField(blank=True, help_text='Designation used on TDS return workpapers.', max_length=80, verbose_name='TDS Responsible Designation'),
        ),
        migrations.AddField(
            model_name='company',
            name='tds_responsible_person',
            field=models.CharField(blank=True, help_text='Person responsible for TDS/TRACES filings.', max_length=120, verbose_name='TDS Responsible Person'),
        ),
    ]
