# Generated by Django 4.2.13 on 2026-05-02 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_company_tan_company_tds_responsible_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTPostFilingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gstr1_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('under_notice', 'Under Notice')], default='not_checked', max_length=20)),
                ('gstr1_arn', models.CharField(blank=True, max_length=160, verbose_name='GSTR-1 ARN')),
                ('gstr1_filed_at', models.DateTimeField(blank=True, null=True)),
                ('gstr3b_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending'), ('filed', 'Filed'), ('accepted', 'Accepted'), ('under_notice', 'Under Notice')], default='not_checked', max_length=20)),
                ('gstr3b_arn', models.CharField(blank=True, max_length=160, verbose_name='GSTR-3B ARN')),
                ('gstr3b_filed_at', models.DateTimeField(blank=True, null=True)),
                ('ims_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('exceptions', 'Exceptions Open')], default='not_checked', max_length=20)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('short_paid', 'Short Paid')], default='pending', max_length=20)),
                ('payment_challan_reference', models.CharField(blank=True, max_length=160)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('itc_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('portal_evidence_reference', models.CharField(blank=True, help_text='ARN, acknowledgement PDF reference, challan CIN, or evidence vault path.', max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_post_filing_trackers', to='core.company')),
                ('pack', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_filing_tracker', to='core.gstfilingpack')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gst_post_filing_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', 'company__name'],
                'indexes': [models.Index(fields=['company', 'period_start'], name='core_gst_post_cmp_period_idx'), models.Index(fields=['gstr1_status', 'gstr3b_status'], name='core_gst_post_return_idx'), models.Index(fields=['payment_status', 'period_start'], name='core_gst_post_pay_idx')],
                'unique_together': {('company', 'period_start', 'period_end')},
            },
        ),
    ]
