# Generated by Django 4.2.13 on 2026-05-02 09:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_gstpostfilingtracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTEvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('evidence_type', models.CharField(choices=[('gstr1_ack', 'GSTR-1 Acknowledgement'), ('gstr3b_ack', 'GSTR-3B Acknowledgement'), ('challan', 'GST Challan / CIN'), ('notice', 'GST Notice'), ('response', 'Notice Response'), ('drc03', 'DRC-03'), ('other', 'Other Evidence')], default='other', max_length=30)),
                ('return_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GST_IMS', 'GST IMS / 2B'), ('NOTICE', 'Notice'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=core.models.gst_evidence_upload_path)),
                ('external_reference', models.CharField(blank=True, max_length=180)),
                ('arn_ack_number', models.CharField(blank=True, max_length=160, verbose_name='ARN / Ack Number')),
                ('challan_reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_evidence_documents', to='core.company')),
                ('filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_evidence_documents', to='core.compliancefiling')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_evidence_documents', to='core.compliancenotice')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_documents', to='core.gstfilingpack')),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_documents', to='core.gstpostfilingtracker')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gst_evidence_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['company', 'period_start'], name='core_gst_evid_cmp_period_idx'), models.Index(fields=['evidence_type', 'return_type'], name='core_gst_evid_type_idx'), models.Index(fields=['arn_ack_number'], name='core_gst_evid_arn_idx')],
            },
        ),
    ]
