# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_gstevidencedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="whatsapp_intake_number",
            field=models.CharField(
                blank=True,
                help_text="Business WhatsApp number clients send documents to, e.g. +919876543210.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="WhatsApp Intake Number",
            ),
        ),
    ]
