# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_company_whatsapp_intake_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="invoice_email_body",
            field=models.TextField(
                blank=True,
                default=(
                    "Dear {client_name},\n\n"
                    "Please find attached invoice {voucher_number} from {company_name} "
                    "for {amount}.\n\n"
                    "Regards,\n{company_name}"
                ),
                help_text="Available placeholders: {voucher_number}, {company_name}, {client_name}, {amount}.",
                verbose_name="Invoice Email Body",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_email_from_address",
            field=models.EmailField(
                blank=True,
                help_text="Sender email used for invoice emails. Leave blank to use the system default.",
                max_length=254,
                null=True,
                verbose_name="Invoice Email Sender Address",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_email_from_name",
            field=models.CharField(
                blank=True,
                help_text="Display name used when sending invoices by email.",
                max_length=120,
                verbose_name="Invoice Email Sender Name",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_email_reply_to",
            field=models.EmailField(
                blank=True,
                help_text="Replies to invoice emails will go to this address. Leave blank to use the sender address.",
                max_length=254,
                null=True,
                verbose_name="Invoice Email Reply-To",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="invoice_email_subject",
            field=models.CharField(
                blank=True,
                default="Invoice {voucher_number} from {company_name}",
                help_text="Available placeholders: {voucher_number}, {company_name}, {client_name}, {amount}.",
                max_length=180,
                verbose_name="Invoice Email Subject",
            ),
        ),
    ]
