# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_company_invoice_email_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="e_invoice_aato_crore",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Aggregate annual turnover used to decide e-invoice applicability.",
                max_digits=8,
                null=True,
                verbose_name="AATO (Rs. crore)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="e_invoice_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable IRN deadline watch for clients covered by GST e-invoicing.",
                verbose_name="E-Invoice Applicable",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="e_invoice_reporting_deadline_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Maximum days from invoice date to report eligible documents on IRP.",
                verbose_name="IRP Reporting Deadline Days",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="e_invoice_warning_days",
            field=models.PositiveSmallIntegerField(
                default=25,
                help_text="Flag invoices without IRN once they cross this age in days.",
                verbose_name="IRP Warning Day",
            ),
        ),
    ]
