# Generated by Django 4.2.13 on 2026-05-03 04:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0024_company_payment_reminder_email_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('onboarding', 'Onboarding'), ('paused', 'Paused'), ('exiting', 'Exiting')], default='active', max_length=20)),
                ('service_package', models.CharField(choices=[('basic_compliance', 'Basic Compliance'), ('gst_tds', 'GST + TDS'), ('full_accounting', 'Full Accounting'), ('virtual_cfo', 'Virtual CFO / Advisory'), ('audit_tax', 'Audit + Tax'), ('custom', 'Custom')], default='gst_tds', max_length=30)),
                ('monthly_retainer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('project', 'Project / One-time')], default='monthly', max_length=20)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('risk_rating', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('scope_summary', models.TextField(blank=True)),
                ('out_of_scope', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='core.company')),
                ('manager_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_engagements', to=settings.AUTH_USER_MODEL)),
                ('partner_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name'],
                'indexes': [models.Index(fields=['status', 'risk_rating'], name='core_engage_status_risk_idx'), models.Index(fields=['renewal_date'], name='core_engage_renewal_idx')],
            },
        ),
    ]
