# Generated by Codex on 2026-05-03

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0025_clientengagement"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyStatutoryProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gst_registered", models.BooleanField(default=True, help_text="Disable GST deadline generation for clients not registered under GST.", verbose_name="GST Registered")),
                ("gst_return_frequency", models.CharField(choices=[("monthly", "Monthly"), ("qrmp", "QRMP / Quarterly")], default="monthly", max_length=20, verbose_name="GSTR-3B Frequency")),
                ("gstr1_frequency", models.CharField(choices=[("monthly", "Monthly"), ("quarterly", "Quarterly")], default="monthly", max_length=20, verbose_name="GSTR-1 Frequency")),
                ("qrmp_group", models.CharField(choices=[("A", "Group A / 22nd"), ("B", "Group B / 24th"), ("CUSTOM", "Custom")], default="A", max_length=10, verbose_name="QRMP State Group")),
                ("gstr1_monthly_due_day", models.PositiveSmallIntegerField(default=11)),
                ("gstr1_quarterly_due_day", models.PositiveSmallIntegerField(default=13)),
                ("gstr3b_monthly_due_day", models.PositiveSmallIntegerField(default=20)),
                ("gstr3b_qrmp_due_day", models.PositiveSmallIntegerField(default=22)),
                ("gst_late_fee_per_day", models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=8)),
                ("gst_nil_late_fee_per_day", models.DecimalField(decimal_places=2, default=Decimal("20.00"), max_digits=8)),
                ("gst_interest_rate_percent", models.DecimalField(decimal_places=2, default=Decimal("18.00"), max_digits=5)),
                ("tds_applicable", models.BooleanField(default=True, verbose_name="TDS Applicable")),
                ("tds_24q_enabled", models.BooleanField(default=False, verbose_name="Form 24Q")),
                ("tds_26q_enabled", models.BooleanField(default=True, verbose_name="Form 26Q")),
                ("tds_27q_enabled", models.BooleanField(default=False, verbose_name="Form 27Q")),
                ("tds_deposit_due_day", models.PositiveSmallIntegerField(default=7)),
                ("tds_march_deposit_due_day", models.PositiveSmallIntegerField(default=30)),
                ("tds_deposit_interest_rate_percent_per_month", models.DecimalField(decimal_places=2, default=Decimal("1.50"), max_digits=5)),
                ("tds_return_late_fee_per_day", models.DecimalField(decimal_places=2, default=Decimal("200.00"), max_digits=8)),
                ("msme_watch_enabled", models.BooleanField(default=True, verbose_name="MSME Watch")),
                ("msme_default_credit_days", models.PositiveSmallIntegerField(default=45)),
                ("msme_interest_rate_percent", models.DecimalField(decimal_places=2, default=Decimal("18.00"), max_digits=5)),
                ("due_date_grace_days", models.PositiveSmallIntegerField(default=0, help_text="Internal grace window for client triage only. It does not change statutory due dates.")),
                ("rules_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="statutory_profile", to="core.company")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_statutory_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Company Statutory Profile",
                "verbose_name_plural": "Company Statutory Profiles",
                "ordering": ["company__name"],
            },
        ),
        migrations.CreateModel(
            name="StatutoryRuleOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rule_type", models.CharField(choices=[("GSTR1", "GSTR-1"), ("GSTR3B", "GSTR-3B"), ("TDS_DEPOSIT", "TDS Deposit"), ("TDS_RETURN_24Q", "TDS Return 24Q"), ("TDS_RETURN_26Q", "TDS Return 26Q"), ("TDS_RETURN_27Q", "TDS Return 27Q"), ("MSME_PAYMENT", "MSME Payment"), ("E_INVOICE", "E-Invoice"), ("OTHER", "Other")], max_length=30)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("original_due_date", models.DateField(blank=True, null=True)),
                ("override_due_date", models.DateField(blank=True, null=True)),
                ("late_fee_per_day", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("interest_rate_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="statutory_rule_overrides", to="core.company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_statutory_rule_overrides", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-is_active", "rule_type", "-period_start", "-updated_at"],
                "indexes": [
                    models.Index(fields=["company", "rule_type", "is_active"], name="core_rule_company_type_idx"),
                    models.Index(fields=["period_start", "period_end"], name="core_rule_period_idx"),
                ],
            },
        ),
    ]
