# Generated by Codex on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_companystatutoryprofile_statutoryruleoverride"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancefiling",
            name="filing_type",
            field=models.CharField(
                choices=[
                    ("GSTR1", "GSTR-1"),
                    ("GSTR3B", "GSTR-3B"),
                    ("GSTR9", "GSTR-9"),
                    ("GSTR9C", "GSTR-9C"),
                    ("GST_IMS", "GST IMS Review"),
                    ("TDS_PAYMENT", "TDS Payment"),
                    ("TDS_24Q", "TDS 24Q"),
                    ("TDS_26Q", "TDS 26Q"),
                    ("TDS_27Q", "TDS 27Q"),
                    ("FORM16", "Form 16"),
                    ("ITR", "ITR"),
                    ("MCA_AOC4", "MCA AOC-4"),
                    ("MCA_MGT7", "MCA MGT-7"),
                    ("TAX_AUDIT", "Tax Audit"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
