# Generated by Django 4.2.13 on 2026-05-03 14:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_alter_compliancefiling_filing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('pilot_call', 'Pilot Call'), ('objection', 'Objection'), ('feature_request', 'Feature Request'), ('bug', 'Bug'), ('workflow_gap', 'Workflow Gap'), ('training', 'Training Need'), ('conversion_signal', 'Conversion Signal')], default='pilot_call', max_length=30)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(default=7, help_text='0 to 10 signal of client confidence in replacing the current workflow.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('summary', models.CharField(max_length=220)),
                ('detail', models.TextField(blank=True)),
                ('client_contact', models.CharField(blank=True, max_length=160)),
                ('competitor_reference', models.CharField(blank=True, choices=[('', 'No direct competitor'), ('tally', 'Tally'), ('zoho', 'Zoho Books'), ('busy', 'Busy'), ('marg', 'Marg'), ('clear', 'Clear'), ('ledger', 'Ledger / Vyapar'), ('spreadsheet', 'Excel / Spreadsheet'), ('other', 'Other')], default='', max_length=30)),
                ('evidence_reference', models.CharField(blank=True, help_text='Call note, ticket id, client quote reference, screen recording, or uploaded evidence link.', max_length=255)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pilot_feedback', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_feedback', to='core.company')),
                ('follow_up_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot_feedback_items', to='core.practicetask')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_pilot_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-occurred_on', 'company__name'],
                'indexes': [models.Index(fields=['company', 'status'], name='core_pfb_cmp_stat_idx'), models.Index(fields=['occurred_on'], name='core_pfb_occ_idx'), models.Index(fields=['feedback_type', 'sentiment'], name='core_pfb_type_sent_idx')],
            },
        ),
    ]
