# Generated by Django 4.2.13 on 2026-05-03 15:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_pilotfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketProofCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Review'), ('approved', 'Approved'), ('published', 'Published'), ('on_hold', 'On Hold')], default='draft', max_length=20)),
                ('outcome', models.CharField(choices=[('evaluating', 'Evaluating'), ('converted', 'Converted'), ('paid', 'Paid'), ('expanded', 'Expanded'), ('paused', 'Paused')], default='evaluating', max_length=20)),
                ('migration_source', models.CharField(choices=[('tally', 'Tally'), ('zoho', 'Zoho Books'), ('busy', 'Busy'), ('spreadsheet', 'Excel / Spreadsheet'), ('manual', 'Manual / Paper'), ('other', 'Other')], default='tally', max_length=30)),
                ('client_contact', models.CharField(blank=True, max_length=160)),
                ('client_role', models.CharField(blank=True, max_length=120)),
                ('testimonial_quote', models.TextField(blank=True)),
                ('publish_consent', models.BooleanField(default=False)),
                ('anonymized', models.BooleanField(default=True)),
                ('consent_reference', models.CharField(blank=True, max_length=180)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('before_process_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('after_process_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('monthly_documents', models.PositiveIntegerField(default=0)),
                ('monthly_invoices', models.PositiveIntegerField(default=0)),
                ('gst_periods_completed', models.PositiveIntegerField(default=0)),
                ('tally_parallel_run_days', models.PositiveIntegerField(default=0)),
                ('cutover_date', models.DateField(blank=True, null=True)),
                ('commercial_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('value_summary', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_market_case_studies', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_case_studies', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_market_case_studies', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_market_case_studies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-updated_at', 'company__name'],
                'indexes': [models.Index(fields=['company', 'status'], name='core_case_cmp_stat_idx'), models.Index(fields=['outcome', 'migration_source'], name='core_case_out_src_idx'), models.Index(fields=['publish_consent', 'status'], name='core_case_consent_idx')],
            },
        ),
    ]
