# Generated by Django 4.2.13 on 2026-05-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0029_marketproofcasestudy"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketProofExternalEvidence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(choices=[("provider_production", "Live Provider Credentials"), ("live_pilot", "Live Pilot Usage"), ("client_case_study", "Client Case Study Proof"), ("statutory_filing", "Statutory Filing Acknowledgement"), ("backup_restore", "Backup / Restore Evidence"), ("security_signoff", "Security / Access Signoff"), ("commercial_commitment", "Commercial Commitment")], max_length=30)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("received", "Received"), ("verified", "Verified"), ("rejected", "Rejected"), ("expired", "Expired")], default="requested", max_length=20)),
                ("source", models.CharField(choices=[("client", "Client"), ("ca_team", "CA Team"), ("provider", "Provider"), ("system", "System"), ("other", "Other")], default="ca_team", max_length=20)),
                ("title", models.CharField(max_length=180)),
                ("evidence_reference", models.CharField(blank=True, help_text="Portal ARN, provider ticket, evidence pack id, signed email reference, or internal artifact id.", max_length=255)),
                ("artifact_sha256", models.CharField(blank=True, max_length=64, verbose_name="Artifact SHA-256")),
                ("evidence_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_external_evidence", to="core.company")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_market_external_evidence", to=settings.AUTH_USER_MODEL)),
                ("follow_up_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="market_external_evidence_items", to="core.practicetask")),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="owned_market_external_evidence", to=settings.AUTH_USER_MODEL)),
                ("verified_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="verified_market_external_evidence", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["status", "due_date", "company__name", "category"],
                "indexes": [
                    models.Index(fields=["company", "category", "status"], name="core_mpe_cmp_cat_stat_idx"),
                    models.Index(fields=["status", "due_date"], name="core_mpe_stat_due_idx"),
                    models.Index(fields=["expires_on"], name="core_mpe_exp_idx"),
                ],
            },
        ),
    ]
