# Generated by Django 5.2.12 on 2026-03-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_ledger_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-character GST Identification Number of this party (for GSTR-1 B2B invoices)', max_length=15, null=True, verbose_name='GSTIN'),
        ),
    ]
