# Generated by Django 4.2.13 on 2026-04-11 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_ledger_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Optional parent account for sub-ledger grouping. Example: 'Bank Accounts' → 'SBI Current Account'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.ledger'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='group',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Income', 'Income'), ('Expense', 'Expense'), ('Equity', 'Equity'), ('Tax', 'Tax')], max_length=20),
        ),
    ]
