# Generated by Django 4.2.13 on 2026-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_add_equity_parent_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='address',
            field=models.TextField(blank=True, help_text='Registered office address or billing address.', null=True),
        ),
    ]
