# Generated by Django 4.2.13 on 2026-04-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_data_migrate_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['account_group__nature', 'name'], 'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledgers'},
        ),
        migrations.RemoveField(
            model_name='ledger',
            name='group',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='account_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='ledger.accountgroup'),
        ),
    ]
