# Generated by Django 4.2.13 on 2026-04-14 20:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_alter_ledger_options_remove_ledger_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='threshold_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Statutory threshold limit for this group (e.g., TDS limit).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-character GST Identification Number of this party (for GSTR-1 B2B invoices)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g., 24AAAAA0000A1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN'),
        ),
    ]
