# Generated by Django 4.2.13 on 2026-04-14 20:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_accountgroup_threshold_limit_alter_ledger_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='pan_number',
            field=models.CharField(blank=True, help_text='10-character Permanent Account Number (required for TDS)', max_length=10, null=True, verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tds_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard TDS rate for this ledger', max_digits=5),
        ),
        migrations.AddField(
            model_name='ledger',
            name='tds_section',
            field=models.CharField(blank=True, help_text='e.g. 194C, 194J, 194H', max_length=10, null=True, verbose_name='TDS Section'),
        ),
    ]
