# Generated by Django 4.2.13 on 2026-04-14 21:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_ledger_pan_number_ledger_tds_rate_ledger_tds_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='tds_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('30000.00'), help_text='Single bill threshold for TDS deduction (e.g. 30000 for 194C)', max_digits=15),
        ),
    ]
