# Generated by Django 4.2.13 on 2026-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_ledger_tds_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email for statutory communications.', max_length=254, null=True),
        ),
    ]
