# Generated by Django 4.2.13 on 2026-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_ledger_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_msme',
            field=models.BooleanField(default=False, help_text='If Yes, payment must be within 45 days (MSMED Act).', verbose_name='Is MSME?'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='msme_reg_number',
            field=models.CharField(blank=True, help_text='Udyam Registration Number (URN).', max_length=50, null=True, verbose_name='MSME Registration'),
        ),
    ]
