# Generated by Django 4.2.13 on 2026-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0013_ledger_is_msme_ledger_msme_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='credit_days',
            field=models.IntegerField(blank=True, help_text='Maximum allowed age of unpaid invoices (in days).', null=True),
        ),
        migrations.AddField(
            model_name='ledger',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total outstanding allowed for this customer.', max_digits=15, null=True),
        ),
    ]
