# Generated by Django 5.2.12 on 2026-03-26 23:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
        ('ledger', '0003_ledger_gstin'),
        ('vouchers', '0005_add_cost_center_to_voucheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('accumulated_depr_ledger', models.ForeignKey(blank=True, help_text='Accumulated Depreciation ledger (contra asset).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_groups_as_accum', to='ledger.ledger')),
                ('asset_ledger', models.ForeignKey(blank=True, help_text='Asset (Balance Sheet) ledger.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_groups_as_asset', to='ledger.ledger')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_groups', to='core.company')),
                ('depreciation_ledger', models.ForeignKey(blank=True, help_text='Depreciation Expense ledger.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_groups_as_depr', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Groups',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_code', models.CharField(blank=True, max_length=30)),
                ('purchase_date', models.DateField()),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('SLM', 'Straight Line Method (SLM)'), ('WDV', 'Written Down Value (WDV)')], default='SLM', max_length=3)),
                ('wdv_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='WDV rate % per year', max_digits=6)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Disposed', 'Disposed')], default='Active', max_length=10)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='fixedassets.assetgroup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='core.company')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2024-25', max_length=7)),
                ('book_value_opening', models.DecimalField(decimal_places=2, max_digits=15)),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value_closing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('posted_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_entries', to='vouchers.voucher')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='fixedassets.fixedasset')),
            ],
            options={
                'verbose_name': 'Asset Depreciation',
                'verbose_name_plural': 'Asset Depreciations',
                'ordering': ['financial_year'],
            },
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['company', 'status'], name='fixedassets_company_94172c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together={('asset', 'financial_year')},
        ),
    ]
