# Generated by Django 4.2.13 on 2026-04-15 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_checklistitem'),
        ('ledger', '0013_ledger_is_msme_ledger_msme_reg_number'),
        ('inventory', '0006_stockvaluationentry_companysettings'),
        ('vouchers', '0020_voucher_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.stockitem')),
                ('vendor', models.ForeignKey(limit_choices_to={'account_group__nature': 'Liability'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='ledger.ledger')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='vouchers.voucher')),
            ],
        ),
    ]
