# Generated by Django 4.2.13 on 2026-03-27 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_auditlog_index_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic (50 Vouchers/mo)'), ('pro', 'Pro (500 Vouchers/mo)'), ('enterprise', 'Enterprise (Unlimited)')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('subscription_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateTimeField()),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('voucher_count_monthly', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.company')),
                ('primary_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Subscription',
                'verbose_name_plural': 'Client Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('expiry_date', models.DateTimeField(help_text='The new subscription end date after this payment.')),
                ('client_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.clientsubscription')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-payment_date'],
            },
        ),
    ]
