"""
core/urls.py
"""

from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("healthz/",                         views.healthz,         name="healthz"),
    path("api/search/",                      views.universal_search, name="api_search"),
    path("chatbot/query/",                   views.chatbot_query,    name="chatbot_query"),
    path("select-company/",                  views.select_company,   name="select_company"),
    path("switch-company/<int:company_id>/", views.switch_company,   name="switch_company"),
    path("dashboard/",                       views.dashboard,        name="dashboard"),
    path("production-trust/",                views.production_trust_center, name="production_trust_center"),
    path("operations-monitor/",              views.operations_monitor, name="operations_monitor"),
    path("system-observability/",            views.system_observability, name="system_observability"),
    path("api/system-observability/",        views.system_observability_api, name="system_observability_api"),
    path("go-live-certificate/",             views.go_live_certificate, name="go_live_certificate"),
    path("api/go-live-certificate/",         views.go_live_certificate_api, name="go_live_certificate_api"),
    path("go-live-certificate/evidence-pack/", views.go_live_evidence_pack_download, name="go_live_evidence_pack"),
    path("security-control/",                views.security_control, name="security_control"),
    path("ca-approval-inbox/",               views.ca_approval_inbox, name="ca_approval_inbox"),
    path("statutory-exposure/",              views.statutory_exposure, name="statutory_exposure"),
    path("client-operating-readiness/",       views.client_operating_readiness, name="client_operating_readiness"),
    path("client-pilot-launch/",             views.client_pilot_launch, name="client_pilot_launch"),
    path("client-success/",                  views.client_success_cockpit, name="client_success_cockpit"),
    path("client-portal-health/",            views.client_portal_health, name="client_portal_health"),
    path("pilot-adoption-evidence/",         views.pilot_adoption_evidence, name="pilot_adoption_evidence"),
    path("pilot-feedback/",                  views.pilot_feedback_register, name="pilot_feedback_register"),
    path("market-proof/evidence-pack/",       views.market_proof_evidence_pack_download, name="market_proof_evidence_pack"),
    path("market-proof/",                    views.market_proof_pack, name="market_proof_pack"),
    path("market-evidence/",                 views.market_external_evidence, name="market_external_evidence"),
    path("market-case-studies/",             views.market_case_studies, name="market_case_studies"),
    path("ca-command-center/autopilot/",      views.ca_command_center_autopilot, name="ca_command_center_autopilot"),
    path("ca-command-center/",               views.ca_command_center, name="ca_command_center"),
    path("partner-review/",                  views.partner_review_cockpit, name="partner_review_cockpit"),
    path("client-360/<int:company_id>/",      views.client_360, name="client_360"),
    path("client-engagements/",              views.client_engagements, name="client_engagements"),
    path("client-engagements/tasks/",        views.client_engagement_alert_tasks, name="client_engagement_alert_tasks"),
    path("client-engagements/<int:company_id>/", views.client_engagement_update, name="client_engagement_update"),
    path("client-profitability/",            views.ca_client_profitability, name="ca_client_profitability"),
    path("statutory-export-center/",          views.statutory_export_center, name="statutory_export_center"),
    path("filing-review-center/",            views.filing_review_center, name="filing_review_center"),
    path("gst-filing-pack/",                 views.gst_filing_pack, name="gst_filing_pack"),
    path("gst-filing-pack/download/<str:kind>/", views.gst_filing_pack_download, name="gst_filing_pack_download"),
    path("gst-post-filing/dashboard/",       views.gst_post_filing_dashboard, name="gst_post_filing_dashboard"),
    path("gst-post-filing/",                 views.gst_post_filing, name="gst_post_filing"),
    path("filing-readiness/",                views.filing_readiness, name="filing_readiness"),
    path("gst-workbench/",                   views.gst_workbench, name="gst_workbench"),
    path("gst-workbench/<int:company_id>/<str:period>/", views.gst_workbench_detail, name="gst_workbench_detail"),
    path("gst-workbench/<int:company_id>/<str:period>/execution-pack/", views.gst_workbench_execution_pack, name="gst_workbench_execution_pack"),
    path("gst-workbench/create-filings/",    views.gst_workbench_create_filings, name="gst_workbench_create_filings"),
    path("gst-workbench/chase-pack/",        views.gst_workbench_chase_pack, name="gst_workbench_chase_pack"),
    path("gst-workbench/signoff/",           views.gst_workbench_signoff, name="gst_workbench_signoff"),
    path("gst-workbench/2b/<int:pk>/action/", views.gst_workbench_2b_action, name="gst_workbench_2b_action"),
    path("gst-workbench/exception-task/",    views.gst_workbench_exception_task, name="gst_workbench_exception_task"),
    path("gst-workbench/client-request/<int:pk>/status/", views.gst_workbench_document_request_status, name="gst_workbench_document_request_status"),
    path("setup-wizard/",                    views.setup_wizard, name="setup_wizard"),
    path("demo-workspace/",                  views.demo_workspace, name="demo_workspace"),
    path("accounting-close/",                 views.accounting_close_workbench, name="accounting_close"),
    path("collections/",                      views.collections_command_center, name="collections_command_center"),
    path("bank-reco-autopilot/",              views.bank_reco_autopilot, name="bank_reco_autopilot"),
    path("tasks/",                           views.practice_task_list, name="practice_tasks"),
    path("tasks/new/",                       views.practice_task_create, name="practice_task_create"),
    path("tasks/<int:pk>/edit/",             views.practice_task_update, name="practice_task_update"),
    path("tasks/<int:pk>/status/",           views.practice_task_set_status, name="practice_task_set_status"),
    path("compliance-calendar/",             views.compliance_calendar, name="compliance_calendar"),
    path("filings/",                         views.compliance_filing_list, name="compliance_filings"),
    path("filings/new/",                     views.compliance_filing_create, name="compliance_filing_create"),
    path("filings/<int:pk>/edit/",           views.compliance_filing_update, name="compliance_filing_update"),
    path("filings/<int:pk>/status/",         views.compliance_filing_set_status, name="compliance_filing_set_status"),
    path("notices/",                         views.compliance_notice_list, name="compliance_notices"),
    path("notices/new/",                     views.compliance_notice_create, name="compliance_notice_create"),
    path("notices/<int:pk>/edit/",           views.compliance_notice_update, name="compliance_notice_update"),
    path("notices/<int:pk>/status/",         views.compliance_notice_set_status, name="compliance_notice_set_status"),
    path("app-settings/",                    views.app_settings, name="app_settings"),
    path("settings/",                        views.company_settings, name="company_settings"),
    path("audit-trail/",                     views.audit_log,        name="audit_log"),

    # ── Bank Reconciliation ───────────────────────────────────────────────────
    path("bank-reconciliation/",
         views.bank_statement_list,       name="bank_statement_list"),
    path("bank-reconciliation/upload/",
         views.bank_statement_upload,     name="bank_statement_upload"),
    path("bank-reconciliation/<int:pk>/",
         views.bank_statement_detail,     name="bank_statement_detail"),
    path("bank-reconciliation/<int:pk>/auto-match/",
         views.bank_statement_auto_match, name="bank_statement_auto_match"),
    path("bank-reconciliation/<int:pk>/bulk-action/",
         views.bank_statement_bulk_action, name="bank_statement_bulk_action"),
    path("bank-reconciliation/<int:pk>/delete/",
         views.bank_statement_delete,     name="bank_statement_delete"),
    path("bank-reconciliation/report/",
         views.bank_reconciliation_report, name="bank_reconciliation_report"),
    path("bank-reconciliation/row/<int:row_pk>/reconcile/",
         views.bank_statement_reconcile,  name="bank_statement_reconcile"),
    path("bank-reconciliation/row/<int:row_pk>/create-voucher/",
         views.create_voucher_from_suggestion, name="create_voucher_from_suggestion"),
    
    # ── Compliance Health ─────────────────────────────────────────────────────
    path("compliance/health/", views.compliance_dashboard, name="compliance_health"),
]
