# Generated by Django 4.2.13 on 2026-04-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vouchers', '0014_alter_voucher_voucher_type'),
        ('core', '0009_companysettings_books_closed_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('BANK', 'Bank Statement'), ('GST', 'GSTR-2B Portal')], max_length=10)),
                ('reference_number', models.CharField(help_text='Transaction Ref or Invoice Number', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING_IN_BOOKS', 'Missing in Books'), ('MISSING_IN_PORTAL', 'Missing in Portal'), ('MISMATCH', 'Amount/Date Mismatch')], default='MISSING_IN_BOOKS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_entries', to='core.company')),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_matches', to='vouchers.voucher')),
            ],
        ),
    ]
