# Generated by Django 4.2.13 on 2026-04-15 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_checklistitem'),
        ('vouchers', '0020_voucher_document'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2BEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15, verbose_name='Supplier GSTIN')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Total GST (IGST or CGST+SGST)', max_digits=15)),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_entries', to='core.company')),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gstr2b_matches', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'GSTR-2B Entry',
                'verbose_name_plural': 'GSTR-2B Entries',
                'unique_together': {('company', 'gstin', 'invoice_number')},
            },
        ),
    ]
