# Generated by Django 4.2.13 on 2026-04-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_checklistitem'),
        ('vouchers', '0021_voucher_po_mismatch_qty_voucher_po_mismatch_rate_and_more'),
        ('reconciliation', '0002_gstr2bentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_entries', to='core.company')),
                ('matched_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_matches', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'Bank Entry',
                'verbose_name_plural': 'Bank Entries',
                'ordering': ['-date'],
            },
        ),
    ]
