# Generated by Django 5.2.12 on 2026-03-25 13:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='inventory_s_stock_i_66ff83_idx',
            old_name='inv_stockledger_item_date_idx',
        ),
        migrations.RenameIndex(
            model_name='stockledger',
            new_name='inventory_s_voucher_96e8fd_idx',
            old_name='inv_stockledger_voucher_idx',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Show alert when closing stock falls below this level. 0 = no alert.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='description',
            field=models.CharField(blank=True, help_text="e.g. 'GST 18%' or 'Exempt'", max_length=100),
        ),
    ]
