# Generated by Django 5.2.12 on 2026-03-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_bank_upi_fields'),
        ('inventory', '0002_rename_inv_stockledger_item_date_idx_inventory_s_stock_i_66ff83_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if this item has no expiry.', null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['stock_item', 'batch_number'],
                'unique_together': {('stock_item', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='stockledger',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch/lot for this movement (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='voucherstockitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch/lot number for this line (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_stock_items', to='inventory.batch'),
        ),
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, help_text='Optional address or description of the location.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godowns', to='core.company')),
            ],
            options={
                'verbose_name': 'Godown',
                'verbose_name_plural': 'Godowns',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockledger',
            name='godown',
            field=models.ForeignKey(blank=True, help_text='Storage location for this movement (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.godown'),
        ),
        migrations.AddField(
            model_name='voucherstockitem',
            name='godown',
            field=models.ForeignKey(blank=True, help_text='Source/destination godown for this line (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_stock_items', to='inventory.godown'),
        ),
    ]
