# Generated by Django 4.2.13 on 2026-04-11 12:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_auditlog_core_auditl_company_def1b0_idx_and_more'),
        ('inventory', '0003_godowns_and_batches'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.company'),
        ),
        migrations.AddField(
            model_name='batch',
            name='godown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.godown'),
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15),
        ),
        migrations.AddField(
            model_name='godown',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='The main warehouse for the company.'),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='prevent_negative_stock',
            field=models.BooleanField(default=False, help_text='If enabled, the system will block transactions that result in negative stock.'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('company', 'stock_item', 'batch_number', 'godown')},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='manufacturing_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='notes',
        ),
    ]
