# Generated by Django 4.2.13 on 2026-04-14 19:24

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings'),
        ('inventory', '0004_alter_batch_unique_together_batch_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('entry_type', models.CharField(choices=[('Adjustment', 'Adjustment'), ('Waste', 'Waste'), ('Production', 'Production'), ('Transfer', 'Transfer')], default='Adjustment', max_length=20)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='core.company')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockitem',
            name='valuation_method',
            field=models.CharField(choices=[('WAC', 'Weighted Average Cost'), ('FIFO', 'First-In, First-Out')], default='WAC', max_length=10),
        ),
        migrations.CreateModel(
            name='StockEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('godown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.godown')),
                ('stock_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockentry')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.stockitem')),
            ],
        ),
    ]
