# Generated by Django 4.2.13 on 2026-04-14 19:31

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_alter_voucheritem_amount_and_more'),
        ('core', '0008_companysettings'),
        ('inventory', '0005_stockentry_stockitem_valuation_method_stockentryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockValuationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_entries', to='inventory.stockitem')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_entries', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'Stock Valuation Entry',
                'verbose_name_plural': 'Stock Valuation Entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation_method', models.CharField(choices=[('FIFO', 'FIFO'), ('AVG', 'Weighted Average')], default='AVG', max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='core.company')),
            ],
            options={
                'verbose_name': 'Company Inventory Settings',
                'verbose_name_plural': 'Company Inventory Settings',
            },
        ),
    ]
