# Generated by Django 4.2.13 on 2026-04-15 21:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0020_voucher_document'),
        ('inventory', '0006_stockvaluationentry_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_extra_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('allocation_method', models.CharField(choices=[('EQUAL', 'Equal split across items'), ('QUANTITY', 'Split by quantity ratio')], default='EQUAL', max_length=10)),
                ('voucher', models.OneToOneField(limit_choices_to={'voucher_type': 'Purchase'}, on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost', to='vouchers.voucher')),
            ],
        ),
    ]
