# Generated by Django 4.2.13 on 2026-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_landedcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, unique=True),
        ),
    ]
