# Generated by Django 5.2.12 on 2026-03-26 20:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('pan_number', models.CharField(blank=True, max_length=10, verbose_name='PAN')),
                ('uan_number', models.CharField(blank=True, max_length=12, verbose_name='UAN (PF)')),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, verbose_name='IFSC')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly Basic Salary (₹).', max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly HRA (₹). Set to 0 to auto-compute from salary structure.', max_digits=12)),
                ('pf_applicable', models.BooleanField(default=True, verbose_name='PF Applicable')),
                ('esi_applicable', models.BooleanField(default=False, verbose_name='ESI Applicable')),
                ('tds_applicable', models.BooleanField(default=False, verbose_name='TDS Applicable')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
                'unique_together': {('company', 'employee_code')},
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Finalized', 'Finalized')], default='Draft', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core.company')),
            ],
            options={
                'verbose_name': 'Payroll Run',
                'verbose_name_plural': 'Payroll Runs',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard, Management', max_length=100)),
                ('hra_pct', models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='HRA as % of Basic (e.g. 40)', max_digits=5)),
                ('da_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DA as % of Basic', max_digits=5)),
                ('special_allowance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('pf_employee_pct', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employee PF contribution % of Basic (capped at ₹1800)', max_digits=5)),
                ('pf_employer_pct', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Employer PF contribution %', max_digits=5)),
                ('esi_employee_pct', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='Employee ESI % of Gross (applies if gross ≤ ₹21,000)', max_digits=5)),
                ('esi_employer_pct', models.DecimalField(decimal_places=2, default=Decimal('3.25'), help_text='Employer ESI %', max_digits=5)),
                ('pt_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Professional Tax (fixed monthly amount, ₹)', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='core.company')),
            ],
            options={
                'verbose_name': 'Salary Structure',
                'verbose_name_plural': 'Salary Structures',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.DecimalField(decimal_places=1, default=Decimal('26.0'), max_digits=5)),
                ('days_worked', models.DecimalField(decimal_places=1, default=Decimal('26.0'), max_digits=5)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('da', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('esi_employee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('esi_employer', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tds', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.employee')),
                ('payroll_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payrollrun')),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.salarystructure')),
            ],
            options={
                'verbose_name': 'Payslip',
                'verbose_name_plural': 'Payslips',
                'ordering': ['employee__name'],
                'unique_together': {('payroll_run', 'employee')},
            },
        ),
    ]
