# Generated by Django 5.2.12 on 2026-03-26 23:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
        ('ledger', '0003_ledger_gstin'),
        ('vouchers', '0005_add_cost_center_to_voucheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('TDS', 'TDS — Tax Deducted at Source'), ('TCS', 'TCS — Tax Collected at Source')], default='TDS', max_length=3)),
                ('section_code', models.CharField(help_text='e.g. 194C, 194J, 206C', max_length=20)),
                ('description', models.CharField(help_text='Nature of payment/collection', max_length=200)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual threshold limit (₹)', max_digits=12)),
                ('rate_individual', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Rate % for Individuals / HUF', max_digits=5)),
                ('rate_company', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Rate % for Companies / Firms', max_digits=5)),
                ('surcharge_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_sections', to='core.company')),
            ],
            options={
                'verbose_name': 'TDS/TCS Section',
                'verbose_name_plural': 'TDS/TCS Sections',
                'ordering': ['section_code'],
                'unique_together': {('company', 'section_code')},
            },
        ),
        migrations.CreateModel(
            name='TDSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('deductee_type', models.CharField(choices=[('Individual', 'Individual / HUF'), ('Company', 'Company / Firm')], default='Company', max_length=12)),
                ('deductible_amount', models.DecimalField(decimal_places=2, help_text='Base amount on which TDS is computed', max_digits=15)),
                ('rate_applied', models.DecimalField(decimal_places=2, help_text='Actual rate % used', max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pan_number', models.CharField(blank=True, max_length=10, verbose_name='Deductee PAN')),
                ('is_deposited', models.BooleanField(default=False)),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=50)),
                ('bsr_code', models.CharField(blank=True, max_length=7, verbose_name='BSR Code')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='core.company')),
                ('deductee_ledger', models.ForeignKey(help_text='Party from whom TDS is deducted / on whom TCS is collected', on_delete=django.db.models.deletion.PROTECT, related_name='tds_entries_as_deductee', to='ledger.ledger')),
                ('tds_ledger', models.ForeignKey(blank=True, help_text='TDS Payable ledger (Liability)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tds_entries_as_tds_payable', to='ledger.ledger')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tds_entries', to='vouchers.voucher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tds.tdssection')),
            ],
            options={
                'verbose_name': 'TDS/TCS Entry',
                'verbose_name_plural': 'TDS/TCS Entries',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['company', 'is_deposited', 'transaction_date'], name='tds_tdsentr_company_e7eb99_idx')],
            },
        ),
    ]
