# Generated by Django 4.2.13 on 2026-05-02 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_company_tan_company_tds_responsible_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSReturnWorkpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('24Q', 'Form 24Q - Salary'), ('26Q', 'Form 26Q - Domestic non-salary'), ('27Q', 'Form 27Q - Non-resident')], default='26Q', max_length=3)),
                ('financial_year_start', models.PositiveIntegerField(help_text='Financial year start year, e.g. 2025 for FY 2025-26.')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('filed', 'Filed'), ('reopened', 'Reopened')], default='draft', max_length=30)),
                ('traces_token', models.CharField(blank=True, max_length=120)),
                ('traces_statement_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('accepted', 'Accepted / Processed'), ('processed_with_default', 'Processed With Default'), ('rejected', 'Rejected')], default='not_checked', max_length=30)),
                ('challan_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('matched', 'Matched'), ('unmatched', 'Unmatched'), ('overbooked', 'Overbooked')], default='not_checked', max_length=30)),
                ('form16_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('not_requested', 'Not Requested'), ('requested', 'Requested'), ('downloaded', 'Downloaded'), ('issued', 'Issued')], default='not_applicable', max_length=30)),
                ('fvu_status', models.CharField(choices=[('not_run', 'Not Run'), ('warnings', 'Warnings'), ('validated', 'Validated'), ('failed', 'Failed')], default='not_run', max_length=30)),
                ('ack_number', models.CharField(blank=True, max_length=160, verbose_name='Acknowledgement Number')),
                ('summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_return_workpapers', to='core.company')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tds_return_workpapers', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tds_return_workpapers', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tds_return_workpapers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TDS Return Workpaper',
                'verbose_name_plural': 'TDS Return Workpapers',
                'ordering': ['-financial_year_start', 'quarter', 'form_type'],
                'indexes': [models.Index(fields=['company', 'form_type', 'financial_year_start', 'quarter'], name='tds_ret_lookup_idx'), models.Index(fields=['status', 'due_date'], name='tds_ret_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tdsreturnworkpaper',
            constraint=models.UniqueConstraint(fields=('company', 'form_type', 'financial_year_start', 'quarter'), name='tds_ret_unique_period'),
        ),
    ]
