# Generated by Django 4.2.13 on 2026-05-02 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_company_tan_company_tds_responsible_designation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tds', '0002_tdsreturnworkpaper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSFilingPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('24Q', 'Form 24Q - Salary'), ('26Q', 'Form 26Q - Domestic non-salary'), ('27Q', 'Form 27Q - Non-resident')], default='26Q', max_length=3)),
                ('financial_year_start', models.PositiveIntegerField(help_text='Financial year start year, e.g. 2025 for FY 2025-26.')),
                ('quarter', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('filed', 'Filed'), ('reopened', 'Reopened')], default='ready', max_length=20)),
                ('summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('validation_snapshot', models.JSONField(blank=True, default=dict)),
                ('export_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ack_number', models.CharField(blank=True, max_length=160, verbose_name='Acknowledgement Number')),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tds_filing_packs', to='core.company')),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_tds_filing_packs', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tds_filing_packs', to=settings.AUTH_USER_MODEL)),
                ('workpaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filing_packs', to='tds.tdsreturnworkpaper')),
            ],
            options={
                'verbose_name': 'TDS Filing Pack',
                'verbose_name_plural': 'TDS Filing Packs',
                'ordering': ['-financial_year_start', 'quarter', 'form_type'],
                'indexes': [models.Index(fields=['company', 'form_type', 'financial_year_start', 'quarter'], name='tds_pack_lookup_idx'), models.Index(fields=['status', 'due_date'], name='tds_pack_status_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tdsfilingpack',
            constraint=models.UniqueConstraint(fields=('company', 'form_type', 'financial_year_start', 'quarter'), name='tds_pack_unique_period'),
        ),
    ]
