# Generated by Django 4.2.13 on 2026-05-02 08:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_ledger_credit_days_ledger_credit_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tds', '0003_tdsfilingpack_tdsfilingpack_tds_pack_unique_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDSPostFilingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_status', models.CharField(choices=[('not_checked', 'Not Checked'), ('pending', 'Pending / In Process'), ('processed', 'Processed Without Default'), ('processed_with_default', 'Processed With Default'), ('rejected', 'Rejected')], default='not_checked', max_length=30)),
                ('status_checked_at', models.DateTimeField(blank=True, null=True)),
                ('traces_request_number', models.CharField(blank=True, max_length=120)),
                ('justification_report_status', models.CharField(choices=[('not_required', 'Not Required'), ('not_requested', 'Not Requested'), ('requested', 'Requested'), ('downloaded', 'Downloaded'), ('reviewed', 'Reviewed')], default='not_required', max_length=30)),
                ('justification_request_number', models.CharField(blank=True, max_length=120)),
                ('justification_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('conso_file_status', models.CharField(choices=[('not_required', 'Not Required'), ('not_requested', 'Not Requested'), ('requested', 'Requested'), ('downloaded', 'Downloaded'), ('reviewed', 'Reviewed')], default='not_required', max_length=30)),
                ('conso_request_number', models.CharField(blank=True, max_length=120)),
                ('conso_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('correction_required', models.BooleanField(default=False)),
                ('correction_reason', models.CharField(blank=True, max_length=240)),
                ('correction_status', models.CharField(choices=[('not_required', 'Not Required'), ('open', 'Open'), ('prepared', 'Prepared'), ('filed', 'Filed'), ('accepted', 'Accepted')], default='not_required', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_filing_tracker', to='tds.tdsfilingpack')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tds_post_filing_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TDS Post-Filing Tracker',
                'verbose_name_plural': 'TDS Post-Filing Trackers',
                'ordering': ['-pack__financial_year_start', 'pack__quarter', 'pack__form_type'],
                'indexes': [models.Index(fields=['statement_status'], name='tds_post_statement_idx'), models.Index(fields=['correction_required', 'correction_status'], name='tds_post_correction_idx')],
            },
        ),
        migrations.CreateModel(
            name='TDSCertificateIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_serial', models.PositiveIntegerField()),
                ('certificate_type', models.CharField(choices=[('16', 'Form 16'), ('16A', 'Form 16A')], default='16A', max_length=4)),
                ('deductee_name', models.CharField(max_length=200)),
                ('deductee_pan', models.CharField(blank=True, max_length=10)),
                ('section_code', models.CharField(blank=True, max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('request_number', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('downloaded', 'Downloaded'), ('pdf_generated', 'PDF Generated'), ('signed', 'Signed'), ('issued', 'Issued'), ('blocked', 'Blocked')], default='pending', max_length=30)),
                ('issue_channel', models.CharField(blank=True, choices=[('', 'Not Issued'), ('email', 'Email'), ('portal', 'Portal'), ('manual', 'Manual')], default='', max_length=20)),
                ('evidence_reference', models.CharField(blank=True, max_length=240)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deductee_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tds_certificate_issues', to='ledger.ledger')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tds_certificates', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='tds.tdsfilingpack')),
            ],
            options={
                'verbose_name': 'TDS Certificate Issue',
                'verbose_name_plural': 'TDS Certificate Issues',
                'ordering': ['pack', 'entry_serial'],
                'indexes': [models.Index(fields=['pack', 'status'], name='tds_cert_pack_status_idx'), models.Index(fields=['deductee_pan'], name='tds_cert_pan_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='tdscertificateissue',
            constraint=models.UniqueConstraint(fields=('pack', 'entry_serial'), name='tds_cert_unique_pack_serial'),
        ),
    ]
