# Generated by Django 5.2.12 on 2026-03-26 20:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
        ('ledger', '0003_ledger_gstin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, help_text='Short code for quick reference, e.g. MKT, SALES, WH.', max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.company')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BudgetHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g. 2024-25', max_length=7)),
                ('period', models.CharField(choices=[('Annual', 'Annual (Full Year)'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December'), ('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March')], default='Annual', max_length=10)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Target amount for this period.', max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_heads', to='core.company')),
                ('ledger', models.ForeignKey(help_text='The ledger account this budget applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='budget_heads', to='ledger.ledger')),
                ('cost_center', models.ForeignKey(blank=True, help_text='Restrict this budget to a specific cost center (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_heads', to='costcenter.costcenter')),
            ],
            options={
                'verbose_name': 'Budget Head',
                'verbose_name_plural': 'Budget Heads',
                'ordering': ['financial_year', 'ledger__name', 'period'],
                'unique_together': {('company', 'ledger', 'cost_center', 'financial_year', 'period')},
            },
        ),
    ]
