# Generated by Django 4.2.13 on 2026-04-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Project, Department, etc.', max_length=100),
        ),
    ]
