# Generated by Django 4.2.13 on 2026-04-15 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_companysettings_bank_locked_until_and_more'),
        ('ledger', '0012_ledger_email'),
        ('costcenter', '0002_costcenter_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostAllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('PERCENTAGE', 'Fixed Percentage'), ('REVENUE', 'Based on Revenue'), ('HEADCOUNT', 'Based on Headcount')], default='PERCENTAGE', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='core.company')),
                ('ledger', models.ForeignKey(blank=True, help_text='The indirect expense ledger to allocate. If blank, applies to all unallocated indirect expenses.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_rules', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Cost Allocation Rule',
                'verbose_name_plural': 'Cost Allocation Rules',
            },
        ),
        migrations.CreateModel(
            name='AllocationPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage (0-100)', max_digits=5)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='costcenter.costcenter')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentages', to='costcenter.costallocationrule')),
            ],
            options={
                'unique_together': {('rule', 'cost_center')},
            },
        ),
    ]
