# Generated by Django 4.2.13 on 2026-04-15 21:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0003_costallocationrule_allocationpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(help_text='1-12 (Jan-Dec)')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='costcenter.costcenter')),
            ],
            options={
                'ordering': ['-year', '-month', 'cost_center__name'],
                'unique_together': {('cost_center', 'year', 'month')},
            },
        ),
    ]
