# Generated by Django 4.2.13 on 2026-04-18 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_checklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='migrations/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('raw_preview', models.JSONField(blank=True, null=True)),
                ('detected_mapping', models.JSONField(blank=True, null=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
