# Generated by Django 4.2.13 on 2026-04-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='vouchers_count',
            field=models.IntegerField(default=0),
        ),
    ]
