# Generated by Django 4.2.13 on 2026-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_importsession_vouchers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='detected_opening_balances',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='opening_balances_count',
            field=models.IntegerField(default=0),
        ),
    ]
