# Generated by Django 4.2.13 on 2026-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_importsession_detected_opening_balances_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='skipped_rows',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='total_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='importsession',
            name='total_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
