# Generated by Django 4.2.13 on 2026-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_importsession_skipped_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='ledger_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
