# Generated by Django 4.2.13 on 2026-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0006_importsession_quality_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='import_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_company_guid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='source_system',
            field=models.CharField(choices=[('tally_excel', 'Tally Excel Export'), ('tally_xml', 'Tally XML Export'), ('generic_excel', 'Generic Excel'), ('generic_csv', 'Generic CSV')], default='tally_excel', max_length=30),
        ),
        migrations.AddField(
            model_name='importsession',
            name='sync_mode',
            field=models.CharField(choices=[('one_time', 'One-time Import'), ('incremental', 'Incremental Sync'), ('replace_period', 'Replace Selected Period')], default='one_time', max_length=30),
        ),
    ]
