# Generated by Django 4.2.13 on 2026-05-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('migration', '0007_importsession_import_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsession',
            name='approval_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_evidence_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_revoke_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_import_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_import_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
