# Generated by Django 4.2.13 on 2026-05-03 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_clientengagement'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_type', models.CharField(choices=[('gst', 'GST Portal'), ('irp', 'IRP / E-Invoice'), ('eway', 'E-Way Bill'), ('traces', 'TRACES'), ('tally', 'Tally Sync')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('provider_name', models.CharField(blank=True, max_length=80)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production'), ('manual', 'Manual / Portal Upload')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('needs_setup', 'Needs Setup'), ('ready', 'Ready'), ('live', 'Live'), ('blocked', 'Blocked')], default='needs_setup', max_length=20)),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('tan', models.CharField(blank=True, max_length=10)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('credential_reference', models.CharField(blank=True, help_text='Reference to a vault/env secret only. Do not store raw API passwords here.', max_length=160)),
                ('credential_last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_connectors', to='core.company')),
            ],
            options={
                'ordering': ['company__name', 'connector_type'],
            },
        ),
        migrations.AlterField(
            model_name='integrationrequestlog',
            name='service',
            field=models.CharField(choices=[('gstin_lookup', 'GSTIN Lookup'), ('e_invoice', 'E-Invoice'), ('e_way_bill', 'E-Way Bill'), ('gst_return', 'GST Return'), ('traces', 'TRACES'), ('tally_sync', 'Tally Sync')], max_length=30),
        ),
        migrations.CreateModel(
            name='StatutoryExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('gstr1_json', 'GSTR-1 JSON'), ('gstr3b_json', 'GSTR-3B JSON'), ('e_invoice_payload', 'E-Invoice Payload'), ('eway_payload', 'E-Way Bill Payload'), ('tds_fvu', 'TDS FVU'), ('tally_sync', 'Tally Sync')], max_length=30)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('validated', 'Validated'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='generated', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(max_length=180)),
                ('file_sha256', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('portal_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_export_logs', to='core.company')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_logs', to='integrations.integrationconnector')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'export_type', 'created_at'], name='stat_export_company_type_idx'), models.Index(fields=['period_start', 'period_end'], name='stat_export_period_idx'), models.Index(fields=['file_sha256'], name='stat_export_sha_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconnector',
            index=models.Index(fields=['company', 'connector_type', 'status'], name='connector_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconnector',
            constraint=models.UniqueConstraint(fields=('company', 'connector_type'), name='unique_company_integration_connector'),
        ),
    ]
