# Generated by Django 4.2.13 on 2026-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationconnector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnector',
            name='connector_type',
            field=models.CharField(choices=[('gst', 'GST Portal'), ('irp', 'IRP / E-Invoice'), ('eway', 'E-Way Bill'), ('traces', 'TRACES'), ('tally', 'Tally Sync'), ('bank_feed', 'Connected Banking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationrequestlog',
            name='service',
            field=models.CharField(choices=[('gstin_lookup', 'GSTIN Lookup'), ('e_invoice', 'E-Invoice'), ('e_way_bill', 'E-Way Bill'), ('gst_return', 'GST Return'), ('traces', 'TRACES'), ('tally_sync', 'Tally Sync'), ('bank_feed', 'Bank Feed')], max_length=30),
        ),
    ]
