# Generated by Django 4.2.13 on 2026-05-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0003_alter_integrationconnector_connector_type_and_more"),
        ("vouchers", "0029_voucher_signed_gst_artifacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationRetryJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("service", models.CharField(choices=[("gstin_lookup", "GSTIN Lookup"), ("e_invoice", "E-Invoice"), ("e_way_bill", "E-Way Bill"), ("gst_return", "GST Return"), ("traces", "TRACES"), ("tally_sync", "Tally Sync"), ("bank_feed", "Bank Feed")], max_length=30)),
                ("provider", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("in_progress", "In Progress"), ("resolved", "Resolved"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="pending", max_length=20)),
                ("priority", models.CharField(choices=[("normal", "Normal"), ("high", "High"), ("critical", "Critical")], default="high", max_length=20)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_error", models.TextField(blank=True)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="integration_retry_jobs", to="core.company")),
                ("connector", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retry_jobs", to="integrations.integrationconnector")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_integration_retry_jobs", to=settings.AUTH_USER_MODEL)),
                ("request_log", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retry_job", to="integrations.integrationrequestlog")),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="resolved_integration_retry_jobs", to=settings.AUTH_USER_MODEL)),
                ("voucher", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="integration_retry_jobs", to="vouchers.voucher")),
            ],
            options={
                "ordering": ["status", "next_attempt_at", "-priority", "-created_at"],
                "indexes": [
                    models.Index(fields=["company", "status", "next_attempt_at"], name="retry_company_status_next_idx"),
                    models.Index(fields=["service", "status"], name="retry_service_status_idx"),
                    models.Index(fields=["connector", "status"], name="retry_connector_status_idx"),
                ],
            },
        ),
    ]
