# Generated by Django 4.2.13 on 2026-03-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date — used for Receivables Aging report.', null=True),
        ),
    ]
