# Generated by Django 5.2.12 on 2026-03-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='reference_voucher',
            field=models.ForeignKey(blank=True, help_text='The Sales/Purchase invoice this line is settling. Leave blank if not applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='vouchers.voucher'),
        ),
    ]
