# Generated by Django 5.2.12 on 2026-03-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0001_initial'),
        ('vouchers', '0004_voucher_gst_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Tag this line to a cost/profit center for department-level reporting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_items', to='costcenter.costcenter'),
        ),
    ]
