# Generated by Django 4.2.13 on 2026-04-11 12:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_batch_unique_together_batch_company_and_more'),
        ('vouchers', '0006_alter_voucher_place_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The specific batch/lot for this stock movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_items', to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='godown',
            field=models.ForeignKey(blank=True, help_text='The warehouse location for this stock movement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_items', to='inventory.godown'),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity for inventory movement.', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per unit for inventory movement.', max_digits=15),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='stock_item',
            field=models.ForeignKey(blank=True, help_text='Optional: link this accounting line to a stock item for inventory tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_items', to='inventory.stockitem'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Stock Transfer', 'Stock Transfer')], max_length=20),
        ),
    ]
