# Generated by Django 4.2.13 on 2026-04-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_voucheritem_batch_voucheritem_godown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheritem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='voucheritem',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2, null=True),
        ),
    ]
