# Generated by Django 4.2.13 on 2026-04-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_data_migrate_dr_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheritem',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='voucheritem',
            name='debit',
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='entry_type',
            field=models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2),
        ),
    ]
