# Generated by Django 4.2.13 on 2026-04-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0010_remove_voucheritem_credit_remove_voucheritem_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheritem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='entry_type',
            field=models.CharField(choices=[('DR', 'Dr'), ('CR', 'Cr')], max_length=2),
        ),
    ]
