# Generated by Django 4.2.13 on 2026-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0011_alter_voucheritem_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
