# Generated by Django 4.2.13 on 2026-04-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0012_voucher_cgst_amount_voucher_igst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='outstanding_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unsettled balance for this voucher.', max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reference_voucher',
            field=models.ForeignKey(blank=True, help_text='Link to another voucher (e.g. Payment link to Invoice)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by', to='vouchers.voucher'),
        ),
    ]
