# Generated by Django 4.2.13 on 2026-04-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0013_voucher_outstanding_amount_voucher_reference_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Sales Return', 'Sales Return'), ('Purchase Return', 'Purchase Return'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Stock Transfer', 'Stock Transfer')], max_length=20),
        ),
    ]
