# Generated by Django 4.2.13 on 2026-04-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companysettings_books_closed_until'),
        ('ledger', '0011_ledger_tds_threshold'),
        ('vouchers', '0014_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voucher_type', models.CharField(choices=[('Payment', 'Payment'), ('Receipt', 'Receipt'), ('Sales', 'Sales'), ('Purchase', 'Purchase'), ('Sales Return', 'Sales Return'), ('Purchase Return', 'Purchase Return'), ('Contra', 'Contra'), ('Journal', 'Journal'), ('Stock Transfer', 'Stock Transfer')], max_length=20)),
                ('tax_behavior', models.CharField(choices=[('AUTO_GST', 'Automatic GST'), ('NONE', 'Manual')], default='AUTO_GST', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_classes', to='core.company')),
                ('default_ledgers', models.ManyToManyField(blank=True, help_text='Ledgers to auto-add to voucher', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Voucher Class',
                'verbose_name_plural': 'Voucher Classes',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_class',
            field=models.ForeignKey(blank=True, help_text='Pre-defined class for auto-tax or default behavior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='vouchers.voucherclass'),
        ),
    ]
