# Generated by Django 4.2.13 on 2026-04-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0015_voucherclass_voucher_voucher_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_itc_claimed',
            field=models.BooleanField(default=False, help_text='For Purchases: Has ITC been realized via GSTR-2B matching?'),
        ),
    ]
