# Generated by Django 4.2.13 on 2026-04-15 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costcenter', '0002_costcenter_category'),
        ('vouchers', '0017_voucher_status_voucher_verified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheritem',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='Tag this line to a specific cost center (Project/Department).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_items', to='costcenter.costcenter'),
        ),
    ]
