# Generated by Django 4.2.13 on 2026-04-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0018_alter_voucheritem_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
