# Generated by Django 4.2.13 on 2026-04-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0019_voucher_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='document',
            field=models.FileField(blank=True, help_text='Attach a scan/PDF of the physical invoice or supporting document.', null=True, upload_to='voucher_docs/'),
        ),
    ]
