# Generated by Django 4.2.13 on 2026-04-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('vouchers', '0020_voucher_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='po_mismatch_qty',
            field=models.BooleanField(default=False, help_text='Flagged if OCR quantity differs from PO.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='po_mismatch_rate',
            field=models.BooleanField(default=False, help_text='Flagged if OCR rate differs from PO.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='po_reference',
            field=models.ForeignKey(blank=True, help_text='Reference Purchase Order for this invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_vouchers', to='orders.order'),
        ),
    ]
