# Generated by Django 4.2.13 on 2026-04-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0021_voucher_po_mismatch_qty_voucher_po_mismatch_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='compliance_notes',
            field=models.TextField(blank=True, help_text='System-generated compliance alerts and audit notes.', null=True),
        ),
    ]
