# Generated by Django 4.2.13 on 2026-04-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0022_voucher_compliance_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='total_tax',
        ),
    ]
