# Generated by Django 4.2.13 on 2026-04-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0023_remove_voucher_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
