# Generated by Django 5.2.12 on 2026-03-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 code, e.g. USD, EUR, GBP', max_length=3)),
                ('name', models.CharField(help_text='e.g. US Dollar', max_length=50)),
                ('symbol', models.CharField(default='$', max_length=5)),
                ('is_base', models.BooleanField(default=False, help_text='Mark as True for the base/home currency (typically INR). Only one per company.')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='core.company')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Effective date of this rate')),
                ('rate', models.DecimalField(decimal_places=6, help_text='How many base-currency units = 1 unit of this currency (e.g. 1 USD = 83.5 INR)', max_digits=18)),
                ('buying_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Bank buying rate (optional)', max_digits=18, null=True)),
                ('selling_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Bank selling rate (optional)', max_digits=18, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. RBI, Manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='forex.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
