# Generated by Django 4.2.13 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(choices=[('RBI', 'RBI (Reserve Bank of India)'), ('SBI', 'SBI (State Bank of India)'), ('FEDAI', "FEDAI (Foreign Exchange Dealers' Association of India)"), ('Customs', 'CBIC (Customs Exchange Rates)'), ('Manual', 'Manual/Other')], default='Manual', help_text='The source or reference for this exchange rate', max_length=50),
        ),
    ]
