# Generated by Django 5.2.12 on 2026-03-26 20:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_bank_reconciliation'),
        ('inventory', '0003_godowns_and_batches'),
        ('ledger', '0003_ledger_gstin'),
        ('vouchers', '0005_add_cost_center_to_voucheritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('Purchase', 'Purchase Order'), ('Sales', 'Sales Order')], max_length=10)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('order_date', models.DateField()),
                ('expected_date', models.DateField(blank=True, help_text='Expected delivery / dispatch date.', null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Partially Fulfilled', 'Partially Fulfilled'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], default='Draft', max_length=25)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.company')),
                ('fulfilled_voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='vouchers.voucher')),
                ('party_ledger', models.ForeignKey(help_text='Supplier (PO) or Customer (SO).', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ledger.ledger')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fulfilled_qty', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.stockitem')),
            ],
            options={
                'verbose_name': 'Order Item',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['company', 'status', 'order_type'], name='orders_orde_company_a3fdbc_idx'),
        ),
    ]
