# Generated by Django 5.2.12 on 2026-03-24 20:02

import django.db.models.deletion
import ocr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload a bill/invoice image (JPG, PNG) or PDF.', upload_to=ocr.models.ocr_upload_path)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw OCR output from Tesseract.')),
                ('parsed_json', models.JSONField(blank=True, default=dict, help_text='Parsed fields: vendor_name, gstin, date, total_amount, vendor_ledger_id, duplicate_warning.')),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('ocr_error', models.TextField(blank=True, help_text='Error message if OCR failed (file still saved).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_submissions', to='core.company')),
                ('linked_voucher', models.OneToOneField(blank=True, help_text='The Purchase Voucher created on Confirm.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_source', to='vouchers.voucher')),
            ],
            options={
                'verbose_name': 'OCR Submission',
                'verbose_name_plural': 'OCR Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
