# Generated by Django 5.2.12 on 2026-03-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrsubmission',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task UUID for tracking async OCR progress.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocrsubmission',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Review'), ('Processing', 'Processing (OCR running…)'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Error', 'Error')], default='Pending', max_length=20),
        ),
    ]
