# Generated by Django 5.2.12 on 2026-03-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocr_task_id_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrsubmission',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Points to the earlier submission this one appears to duplicate.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='ocr.ocrsubmission'),
        ),
    ]
