# Generated by Django 4.2.13 on 2026-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditlog_index_together'),
        ('ocr', '0004_ocrsubmission_extracted_matched_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrsubmission',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the uploaded file to prevent duplicates.', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='ocrsubmission',
            unique_together={('company', 'file_hash')},
        ),
    ]
