# Generated by Django 4.2.13 on 2026-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_ocrsubmission_file_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrsubmission',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Raw text extracted from the document.'),
        ),
    ]
