# Generated by Django 4.2.13 on 2026-04-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_alter_ocrsubmission_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrsubmission',
            name='source',
            field=models.CharField(choices=[('web', 'Web Upload'), ('whatsapp', 'WhatsApp')], default='web', help_text='Origin of the document upload.', max_length=20),
        ),
    ]
